services:
  php:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html/
    ports:
      - 3000:80
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
